
const themeColor = {
    light: {
        primary:"#644d00",
        primaryLight:"#755a00",
        primaryLighter:"#866700",
        primaryLightest:"#977400",
        onPrimary:"#ffffff",
        primaryContainer:"#ffdf92",
        onPrimaryContainer:"#241a00",
        secondary:"#516526",
        onSecondary:"#ffffff",
        secondaryContainer:"#d3ec9e",
        onSecondaryContainer:"#141f00",
        tertialy:"#535a92",
        onTertialy:"#ffffff",
        tertialyContainer:"#dfe0ff",
        onTertialyContainer:"#0d154b",
        error:"#ba1a1a",
        onError:"#ffffff",
        errorContainer:"#ffdad6",
        onErrorContainer:"#410002",
        surface:"#fff8f1",
        surfaceContainer: "#f6eddf",
        surfaceContainerHigh: "#f0e7d9",
        surfaceDim:"#e1d9ce",
        surfaceDimDark:"#dad0c2",
        surfaceBright:"#fff8f1",
        outline:"#7f7665",
        outlineVariant:"#cdc6b4",
        header: "#f0eadc",
    },

    dark: {
        primary:"#e5c36c",
        primaryDark:"#e2bd5e",
        primaryDarker:"#e0b74f",
        primaryDarkest:"#ddb141",
        onPrimary:"#3e2e00",
        onPrimaryLight:"#523d00",
        primaryContainer:"#594400",
        onPrimaryContainer:"#ffdf92",
        secondary:"#b8cf84",
        onSecondary:"#253500",
        secondaryContainer:"#3a4d10",
        onSecondaryContainer:"#d3ec9e",
        tertialy:"#bcc2ff",
        onTertialy:"#242b61",
        tertialyContainer:"#3b4279",
        onTertialyContainer:"#dfe0ff",
        error:"#ffb4ab",
        onError:"#690005",
        errorContainer:"#93000a",
        onErrorContainer:"#ffdad6",
        surface:"#231e15",
        surfaceDim:"#16130d",
        surfaceBright:"#3d3931",
        outline:"#99907e",
        header: "#30270e",
    }
}

export default themeColor;