
const themeColor = {
    light: {
        primary:"#644d00",
        primaryLight:"#755a00",
        primaryLighter:"#866700",
        primaryLightest:"#977400",
        onPrimary:"#ffffff",
        primaryContainer:"#ffdf92",
        primaryContainerDark:"#f9d170",
        primaryContainerDarker: "#e8bf59",
        onPrimaryContainer:"#241a00",
        secondary:"#516526",
        onSecondary:"#ffffff",
        secondaryContainer:"#d3ec9e",
        onSecondaryContainer:"#141f00",
        tertialy:"#535a92",
        onTertialy:"#ffffff",
        tertialyContainer:"#dfe0ff",
        onTertialyContainer:"#0d154b",
        error:"#ba1a1a",
        onError:"#ffffff",
        errorContainer:"#ffdad6",
        onErrorContainer:"#410002",
        surface:"#fff8f1",
        surfaceContainer: "#f6eddf",
        surfaceContainerHigh: "#f0e7d9",
        surfaceContainerHighest:"#eae1d4",
        surfaceContainerLow:"#fcf2e5",
        surfaceDim:"#e1d9ce",
        surfaceDimDark:"#dad0c2",
        surfaceBright:"#fff8f1",
        onSurface:"#1f1b13",
        onSurfaceVariant:"#4c4639",
        outline:"#7f7665",
        outlineVariant:"#cdc6b4",
    },

    dark: {
        primary:"#e5c36c",
        primaryDark:"#e2bd5e",
        primaryDarker:"#e0b74f",
        primaryDarkest:"#ddb141",
        onPrimary:"#3e2e00",
        onPrimaryDeep:"#2b2513",
        onPrimaryLight:"#523d00",
        primaryContainer:"#594400",
        primaryContainerLight: "#6d5300",
        primaryContainerLighter:"#816200",
        onPrimaryContainer:"#ffdf92",
        secondary:"#b8cf84",
        onSecondary:"#253500",
        secondaryContainer:"#3a4d10",
        onSecondaryContainer:"#d3ec9e",
        tertialy:"#bcc2ff",
        onTertialy:"#242b61",
        tertialyContainer:"#3b4279",
        onTertialyContainer:"#dfe0ff",
        error:"#ffb4ab",
        onError:"#690005",
        errorContainer:"#93000a",
        onErrorContainer:"#ffdad6",
        surface:"#16130b",
        surfaceContainer: "#231f17",
        surfaceContainerHigh: "#2e2a21",
        surfaceContainerHighest:"#39342b",
        surfaceContainerLow:"#1f1b13",
        surfaceDim:"#16130b",
        surfaceBright:"#3d392f",
        onSurface:"#eae1d4",
        onSurfaceVariant:"#cfc5b4",
        outline:"#99907e",
        outlineVariant:"#4c4639",
    }
}

export default themeColor;